### ISSUE TITLE
Blank page on unsuccessful installation

### ISSUE THREAD

**Issue by aschempp** [contao/installation-bundle#7]
If the `parameters.yml` file exists but is invalid, the install tool will simply show an empty page. It would probably make sense to try-catch the kernel booting in the `install.php`

**Comment by leofeyer** [comment]
Do you mean the `ParseException`?

**Comment by aschempp** [comment]
I didn't get a `ParseException`, I just got a blank page…

**Comment by leofeyer** [comment]
How was the `parameters.yml` file invalid in your case?

**Comment by aschempp** [comment]
As far as I remember, it was created using composer but I simply skipped all the values (DB etc. was null).
This is probably/actually related to the new behavior of the install tool that does not allow to modify existing values…

**Comment by leofeyer** [comment]
I actually cannot reproduce the issue. The parameters file looks like this after skipping all the values on the command line:

``` yml
# This file is auto-generated during the composer install
parameters:
    secret: …
    database_host: localhost
    database_port: 3306
    database_user: null
    database_password: null
    database_name: null
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_port: 25
    mailer_encryption: null
    prepend_locale: false
```

When I open the install tool, it asks me for the DB credentials, which is correct.
